<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin                                Dashboard</name>
   <tag></tag>
   <elementGuidId>76791df0-6b38-48a6-afb5-49273efe76a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-admin-dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link-admin-dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae2b6c04-5f4b-4839-abc7-1536e0198079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-admin-dashboard</value>
      <webElementGuid>50711c61-ba42-42d7-9ee3-a9d9c1c6878c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alfazatitania.com/admin</value>
      <webElementGuid>9acbe3ec-26f0-4ad9-8a9d-4aa964259874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white</value>
      <webElementGuid>25713853-de53-4d7c-803a-fb2144ac5674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin
                                Dashboard</value>
      <webElementGuid>fab2e938-a0b4-456f-adca-56936c1882b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-admin-dashboard&quot;)</value>
      <webElementGuid>52937e2a-5c1e-4e9b-99f5-fc23867fb594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-admin-dashboard']</value>
      <webElementGuid>50f1534f-9c71-4b95-99c0-b7e9e74e6447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-dropdown']/ul/li/a</value>
      <webElementGuid>2ef32e77-8913-472c-b70e-b076efd38edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin
                                Dashboard')]</value>
      <webElementGuid>4479d7eb-9936-4456-a952-ff90def1cb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>483ee32c-48ee-4bcf-9dc7-593d16b57e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/following::a[1]</value>
      <webElementGuid>5eed1e81-a400-4ae0-a127-dc79ae5955f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>019946b0-f98c-4ffb-a8cd-651fa03e7309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alfazatitania.com/admin')]</value>
      <webElementGuid>c38c39da-7a4f-46f5-977c-151625b22bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>2a1bf522-70d8-498f-ac32-f800e4fd77ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-admin-dashboard' and @href = 'https://alfazatitania.com/admin' and (text() = 'Admin
                                Dashboard' or . = 'Admin
                                Dashboard')]</value>
      <webElementGuid>acca75f6-3109-41cb-a2ad-97477993b742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
