<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_burger</name>
   <tag></tag>
   <elementGuidId>3f5bac70-20ad-41d6-a053-931379ea5045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-justify.fs-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3836e3f4-a5da-4668-83fa-f1e881dc2e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-justify fs-3</value>
      <webElementGuid>da0e5612-6bd6-4304-8408-9726401564af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;mb-3&quot;]/a[@class=&quot;burger-btn d-block d-xl-none&quot;]/i[@class=&quot;bi bi-justify fs-3&quot;]</value>
      <webElementGuid>0cb06be7-93d0-4bbd-8155-1a22fcb8416d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/a/i</value>
      <webElementGuid>43e43784-9748-4ace-b36d-0fc12e9d7489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/i</value>
      <webElementGuid>73deb08e-c2ed-4a6a-ae3f-8fba2f3f5ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
