<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_icon_profile</name>
   <tag></tag>
   <elementGuidId>96bc23be-c252-4cbc-b0bc-166899825b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-8.h-8.rounded-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='user-menu-button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a965c48-cb34-4c85-adff-7b184d9bb9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-8 h-8 rounded-full</value>
      <webElementGuid>ec8ee755-d287-4118-be96-9bf086d816b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui-avatars.com/api/?name=admin</value>
      <webElementGuid>11f1a33e-3374-4493-9666-4036a841f256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user photo</value>
      <webElementGuid>469c6b14-1732-456d-a778-7ed5366051cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu-button&quot;)/img[@class=&quot;w-8 h-8 rounded-full&quot;]</value>
      <webElementGuid>ad80523d-ba9c-4c88-867d-8f5c9b0e9ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='user-menu-button']/img</value>
      <webElementGuid>4cecb6d8-d659-4d36-bd68-d6b72b0817fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user photo']</value>
      <webElementGuid>1ab0f18f-a54b-45e2-b644-750a02780f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>11021fdb-0378-47ca-a45d-d17f91a45bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ui-avatars.com/api/?name=admin' and @alt = 'user photo']</value>
      <webElementGuid>97eeb1d8-9392-4e8e-bff7-c86e3af336c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
