<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_burger</name>
   <tag></tag>
   <elementGuidId>d2a5a0f8-4ea9-41f8-9c61-db2be88d452f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-justify.fs-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>99ee5a9f-0e2e-436b-aabb-ca6b27031555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-justify fs-3</value>
      <webElementGuid>35e5cc1c-fa78-4a3d-8d8d-9aaa30f3eb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;mb-3&quot;]/a[@class=&quot;burger-btn d-block d-xl-none&quot;]/i[@class=&quot;bi bi-justify fs-3&quot;]</value>
      <webElementGuid>bd0a952c-01e1-4269-b69a-c0d1b67458df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/a/i</value>
      <webElementGuid>4c393bbd-7e62-44ee-86e0-52695057fbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/i</value>
      <webElementGuid>23308c32-4ba7-4562-b6e7-51c973e47053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
