<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_bi bi-justify fs-3</name>
   <tag></tag>
   <elementGuidId>b8022f3b-9eb7-46b0-8bd7-b4762eb33aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-justify.fs-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>90063ee9-2842-4c93-b330-89640d37ac7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-justify fs-3</value>
      <webElementGuid>f49483e5-e911-4ddf-a017-e10f2458d2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;mb-3&quot;]/a[@class=&quot;burger-btn d-block d-xl-none&quot;]/i[@class=&quot;bi bi-justify fs-3&quot;]</value>
      <webElementGuid>775e6504-32f2-49fb-ae43-9214f61fb2b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/a/i</value>
      <webElementGuid>e308939a-4e50-453e-a780-54f11e2022b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a/i</value>
      <webElementGuid>f31ff2ba-ce28-40a1-8b8f-d4c21b87a9e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
