<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin                                Dashboard</name>
   <tag></tag>
   <elementGuidId>e8e8f31a-d687-4654-9b2a-5cedf0a63ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-admin-dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link-admin-dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df4737a5-2b73-44d0-af97-1857e19ae26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-admin-dashboard</value>
      <webElementGuid>1fdf1e2f-5c29-4e68-905a-7f78fa5559b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qas.alfazatitania.com/admin</value>
      <webElementGuid>1ccba79a-56f1-4218-b759-98f28570b5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white</value>
      <webElementGuid>76ed06f1-6ee4-48c0-82c0-7fa364064fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin
                                Dashboard</value>
      <webElementGuid>279dd1e6-b40f-4140-abf2-952100127258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-admin-dashboard&quot;)</value>
      <webElementGuid>0ad22c89-f8ac-4c5e-a6ad-20eedec4700a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-admin-dashboard']</value>
      <webElementGuid>8ad7242d-76d1-4177-b4c0-a876aca3d8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-dropdown']/ul/li/a</value>
      <webElementGuid>888ccc52-e23c-4ba1-8d33-83c90810ca87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin
                                Dashboard')]</value>
      <webElementGuid>8c3e5aec-232e-4912-9865-37dac4960545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>2d7e0e43-f546-441c-b4ab-1a3d7f080682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/following::a[1]</value>
      <webElementGuid>732ac386-8434-425b-94d6-825c6f636eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>0912766a-5552-442d-90cf-1f216ff238ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qas.alfazatitania.com/admin')]</value>
      <webElementGuid>5899f1d3-02fe-4009-8275-9c76cd832c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>53146979-08be-41fb-839e-46cef9bdaeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-admin-dashboard' and @href = 'https://qas.alfazatitania.com/admin' and (text() = 'Admin
                                Dashboard' or . = 'Admin
                                Dashboard')]</value>
      <webElementGuid>5076995d-ee74-4293-b06f-7a40eca3c5ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
