<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin                                Dashboard</name>
   <tag></tag>
   <elementGuidId>38e5ec35-71d6-4113-80a7-5ccc2ae5408a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-admin-dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link-admin-dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8dc14ec-6fa1-42d3-a75d-2ace52b7f3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-admin-dashboard</value>
      <webElementGuid>fa777fdb-df0b-4ed0-b7b1-dc6b55ade265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qas.alfazatitania.com/admin</value>
      <webElementGuid>a4070e90-ebc4-4f5c-ba47-a2d1232d7f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white</value>
      <webElementGuid>0371a533-3910-4a32-94ea-14121d0e739b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin
                                Dashboard</value>
      <webElementGuid>ad0bcff3-6fa4-485b-a176-b49840ed5cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-admin-dashboard&quot;)</value>
      <webElementGuid>3cf2a120-af36-44e9-9002-cfd30d1d93e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-admin-dashboard']</value>
      <webElementGuid>09c6a32c-e44f-4860-8054-4685c557eba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-dropdown']/ul/li/a</value>
      <webElementGuid>eb1b908e-7f42-467f-89c6-7ea971a43b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin
                                Dashboard')]</value>
      <webElementGuid>ebecc0dc-f59e-47e5-a82d-d4b333fc5af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>ad81df93-4edc-4c72-93ee-f571cf09815e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/following::a[1]</value>
      <webElementGuid>e4e213aa-cc4b-4032-9240-82d87e440dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>155ef865-e098-4331-b6cb-4f915be67165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qas.alfazatitania.com/admin')]</value>
      <webElementGuid>3b8d1c7c-b95b-46f3-9678-c2497f697987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>738296e2-cff5-4f99-a758-46fe48c084ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-admin-dashboard' and @href = 'https://qas.alfazatitania.com/admin' and (text() = 'Admin
                                Dashboard' or . = 'Admin
                                Dashboard')]</value>
      <webElementGuid>e600ee47-a46d-4e13-af57-e9133d5be8fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
