<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_admin_dashboard</name>
   <tag></tag>
   <elementGuidId>fe27b7b9-1b89-4d5b-a215-a739c27fec51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link-admin-dashboard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-admin-dashboard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36eea78d-a383-4b26-b711-52958b68dfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-admin-dashboard</value>
      <webElementGuid>b185c27f-dffc-4174-8b7b-f82e05af2466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qas.alfazatitania.com/admin</value>
      <webElementGuid>3e70d536-c6ce-4e84-8698-bf058366d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white</value>
      <webElementGuid>3223147a-56b0-47fd-8df3-fb1727cb18d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin
                                Dashboard</value>
      <webElementGuid>ec6e7080-5204-4346-8cca-eb15cee52300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-admin-dashboard&quot;)</value>
      <webElementGuid>45c60ddb-576d-4f2f-b273-09f1319d9cb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-admin-dashboard']</value>
      <webElementGuid>f5f97a36-b925-4870-b73c-0ce0be13b290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-dropdown']/ul/li/a</value>
      <webElementGuid>4d5208c8-8e93-40e9-8d79-f2e6026c5123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin
                                Dashboard')]</value>
      <webElementGuid>a3c12523-fc63-4c4e-8b1a-f9d023a9e38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>66ee001b-541d-4f7b-ad73-0e55ee9da420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/following::a[1]</value>
      <webElementGuid>0b2ca39e-4924-4577-a248-78e5d2cf9f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>fa800db0-d6d0-4f59-8eef-54025797f60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qas.alfazatitania.com/admin')]</value>
      <webElementGuid>aa6b3f36-3a46-45fe-a840-678ac9008a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>2de290a6-895c-41b7-bfc7-61b850f04de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-admin-dashboard' and @href = 'https://qas.alfazatitania.com/admin' and (text() = 'Admin
                                Dashboard' or . = 'Admin
                                Dashboard')]</value>
      <webElementGuid>da538bdb-c68b-42c4-a762-b679d4be042a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
