<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_icon_profile</name>
   <tag></tag>
   <elementGuidId>91b48ef9-86e6-41c1-a39f-c7735c8a69ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-8.h-8.rounded-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='user-menu-button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f2aea7a-65c4-4ddf-93f3-8b87b8954d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-8 h-8 rounded-full</value>
      <webElementGuid>e4378e6f-a5f9-4997-a9a5-bf7d4cbe78d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui-avatars.com/api/?name=admin</value>
      <webElementGuid>03a63271-eaa4-4f13-91ab-b3f9535db52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user photo</value>
      <webElementGuid>5f3fa6e0-68bd-46f1-8e98-a5f0da824e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-menu-button&quot;)/img[@class=&quot;w-8 h-8 rounded-full&quot;]</value>
      <webElementGuid>f0fcb01f-eccb-4e79-8a4d-1e81ae3e6788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='user-menu-button']/img</value>
      <webElementGuid>2b949f81-40fa-417d-84e6-316b0f5a92d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user photo']</value>
      <webElementGuid>102d94ad-757c-4777-8df6-31986d84b2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f16a759b-6413-4c22-bd5d-3dcd4579675c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ui-avatars.com/api/?name=admin' and @alt = 'user photo']</value>
      <webElementGuid>ff198c81-4de6-4e4a-ba10-88af9a0c5b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
