<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin                                Dashboard</name>
   <tag></tag>
   <elementGuidId>b8c1b19a-6a07-45a5-b22d-b14b82aaf62a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-admin-dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#link-admin-dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0923f233-4c25-45f1-acb8-1a999478e19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-admin-dashboard</value>
      <webElementGuid>d7f72994-8d41-44b4-a4e6-23811ae259c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qas.alfazatitania.com/admin</value>
      <webElementGuid>b2a26ecd-9ff7-48fa-b3f2-46b45bda20ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white</value>
      <webElementGuid>2f6cc090-a112-494b-affb-af4adc2b6994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin
                                Dashboard</value>
      <webElementGuid>11543394-059a-4397-9bd7-8e64d92dc00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-admin-dashboard&quot;)</value>
      <webElementGuid>b041b161-e23b-4930-b771-a0ab0611096c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-admin-dashboard']</value>
      <webElementGuid>01aafcbd-2c5a-48c4-8c8f-b3a593ee58b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-dropdown']/ul/li/a</value>
      <webElementGuid>abb32dc3-3a3a-4b9c-98d7-6607b2d120a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin
                                Dashboard')]</value>
      <webElementGuid>632d37ae-eced-42b4-9533-dae134e49bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>e55e6d85-b71c-4222-ad98-16a8891fef2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[1]/following::a[1]</value>
      <webElementGuid>9fa77e7d-558b-474c-a3fb-16124171e0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>9e8c1610-f1ec-4441-a873-8bb451fe9b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://qas.alfazatitania.com/admin')]</value>
      <webElementGuid>be10403c-4c4d-4349-ac89-55e894989d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>75a0305e-b70b-4f9a-8999-bbf906a43d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-admin-dashboard' and @href = 'https://qas.alfazatitania.com/admin' and (text() = 'Admin
                                Dashboard' or . = 'Admin
                                Dashboard')]</value>
      <webElementGuid>d58bc14b-608a-4280-845f-2667637aa4f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
